// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsk-LYiB6DT5H0ff0RRmyX9AJTSzXIPKw',
    appId: '1:613455590936:web:e55b92e81173141f78756d',
    messagingSenderId: '613455590936',
    projectId: 'assign1-5a4ca',
    authDomain: 'assign1-5a4ca.firebaseapp.com',
    storageBucket: 'assign1-5a4ca.appspot.com',
    measurementId: 'G-YD81P734WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYCHu1Nyj7Xsw9uCpUAmnOd3gNefvMEU',
    appId: '1:613455590936:android:6b7bfa4d57e9228e78756d',
    messagingSenderId: '613455590936',
    projectId: 'assign1-5a4ca',
    storageBucket: 'assign1-5a4ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARp0QNX42VnHs93RBxK446v2lgZ9aUh4A',
    appId: '1:613455590936:ios:e4a643e4577de1fb78756d',
    messagingSenderId: '613455590936',
    projectId: 'assign1-5a4ca',
    storageBucket: 'assign1-5a4ca.appspot.com',
    iosBundleId: 'com.example.assgn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARp0QNX42VnHs93RBxK446v2lgZ9aUh4A',
    appId: '1:613455590936:ios:b9d64356d75edd4578756d',
    messagingSenderId: '613455590936',
    projectId: 'assign1-5a4ca',
    storageBucket: 'assign1-5a4ca.appspot.com',
    iosBundleId: 'com.example.assgn1.RunnerTests',
  );
}
